#! /usr/bin/perl -w
my %map = ( 
"(())" => "(())",
"(*)" => "(*)",
"(8)" => "(8)",
"(80)" => "(80)",
"(SOUND)" => "(SOUND)",
"+88+" => "+88+",
"+AA+" => "+AA+",
"+AAA+" => "+AAA+",
"+AH+" => "+AH+",
"+AHH+" => "+AHH+",
"+AHHH+" => "+AHHH+",
"+AHM+" => "+AHM+",
"+AM+" => "+AM+",
"+ARGH+" => "+ARGH+",
"+ARRR+" => "+ARRR+",
"+ATTRACTING+" => "+ATTRACTING+",
"+BEWEWE+" => "+BEWEWE+",
"+BLAH+" => "+BLAH+",
"+BLUEEE+" => "+BLUEEE+",
"+BOOM+" => "+BOOM+",
"+BREATH+" => "+BREATH+",
"+CH+" => "+CH+",
"+CLOSE+" => "+CLOSE+",
"+CO2+" => "+CO2+",
"+DADADA+" => "+DADADA+",
"+DOIE+" => "+DOIE+",
"+EEE+" => "+EEE+",
"+EEEE+" => "+EEEE+",
"+EH+" => "+EH+",
"+ER+" => "+ER+",
"+ERRR+" => "+ERRR+",
"+HA+" => "+HA+",
"+HAHA+" => "+HAHA+",
"+HAHAHA+" => "+HAHAHA+",
"+HELLO+" => "+HELLO+",
"+HM+" => "+HM+",
"+HMM+" => "+HMM+",
"+HOOP+" => "+HOOP+",
"+HUH+" => "+HUH+",
"+HUM+" => "+HUM+",
"+KAPISH+" => "+KAPISH+",
"+MM+" => "+MM+",
"+MMMM+" => "+MMMM+",
"+MOVE+" => "+MOVE+",
"+NO+" => "+NO+",
"+OH+" => "+OH+",
"+OHH+" => "+OHH+",
"+OHHH+" => "+OHHH+",
"+OOOOH+" => "+OOOOH+",
"+OP+" => "+OP+",
"+PHEW+" => "+PHEW+",
"+POP+" => "+POP+",
"+PRODUCT+" => "+PRODUCT+",
"+PRRRRRRR+" => "+PRRRRRRR+",
"+SHAKALAKA+" => "+SHAKALAKA+",
"+SHH+" => "+SHH+",
"+SHHH+" => "+SHHH+",
"+SPACERS+" => "+SPACERS+",
"+SSS+" => "+SSS+",
"+SSSHHHH+" => "+SSSHHHH+",
"+SSSS+" => "+SSSS+",
"+SWITCH+" => "+SWITCH+",
"+TADA+" => "+TADA+",
"+TH+" => "+TH+",
"+TRPTRP+" => "+TRPTRP+",
"+TUDO+" => "+TUDO+",
"+TUTUTO+" => "+TUTUTO+",
"+UH+" => "+UH+",
"+UHH+" => "+UHH+",
"+UHM+" => "+UHM+",
"+UHU+" => "+UHU+",
"+UM+" => "+UM+",
"+UMM+" => "+UMM+",
"+USH+" => "+USH+",
"+UU+" => "+UU+",
"+VERY+" => "+VERY+",
"+WHOA+" => "+WHOA+",
"+WHOO+" => "+WHOO+",
"+WO+" => "+WO+",
"+WOO+" => "+WOO+",
"+WOOO+" => "+WOOO+",
"+WOWO+" => "+WOWO+",
"+WUHU+" => "+WUHU+",
"+YAM+" => "+YAM+",
"+YES+" => "+YES+",
"+YO+" => "+YO+",
"<AH>" => "<AH>",
"<AT>" => "<AT>",
"<BREATH>" => "<BREATH>",
"<BREATHE>" => "<BREATHE>",
"<COUGH>" => "<COUGH>",
"<DISCARD>" => "<DISCARD>",
"<DISTURBANCE>" => "<DISTURBANCE>",
"<ECHO>" => "<ECHO>",
"<FP>" => "<FP>",
"<FSSSSSSHHH>" => "<FSSSSSSHHH>",
"<HA>" => "<HA>",
"<HUM>" => "<HUM>",
"<INAUDIBLE>" => "<INAUDIBLE>",
"<INDISCERNIBLE>" => "<INDISCERNIBLE>",
"<INDISCERNIBLEY>" => "<INDISCERNIBLEY>",
"<INDISCREET>" => "<INDISCREET>",
"<LAUGH>" => "<LAUGH>",
"<MUSIC>" => "<MUSIC>",
"<NOISE>" => "<NOISE>",
"<NOSIE>" => "<NOSIE>",
"<NO_SIGNAL>" => "<NO_SIGNAL>",
"<NO_SPEECH>" => "<NO_SPEECH>",
"<NO_VOICE>" => "<NO_VOICE>",
"<PHRRR>" => "<PHRRR>",
"<SIDE_SPEECH>" => "<SIDE_SPEECH>",
"<SIED_SPEECH>" => "<SIED_SPEECH>",
"<SILENCE>" => "<SILENCE>",
"<SINGING>" => "<SINGING>",
"<SNIFF>" => "<SNIFF>",
"<UMM>" => "<UMM>",
"<UNAUDIBLE>" => "<UNAUDIBLE>",
"<WHISPER>" => "<WHISPER>",
"<YAWN>" => "<YAWN>"
);

# https://www.perlmonks.org/?node_id=1179840

my ($regex) = map { qr/$_/ } 
    join '|', map {quotemeta}
    sort { length $b <=> length $a
           or $a cmp $b }
    keys %map;

while (<>) {
  s/($regex)/$map{$1}/g;
  print $_;
}

